global_frame: base_frame
robot_base_frame: base_frame
rolling_window: false
width: 15
height: 15
origin_x: 0.0
origin_y: -6.0

plugins:
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
